language: node_js
addons:
  firefox: latest
node_js:
  - "10"
  - "12"
cache: npm
before_install: npm install -g nyc codecov
script:
  - npm run test:browser:firefox
  - npm run test:cover
after_success:
  - nyc report --reporter=json > coverage/coverage.json
  - codecov
